In [128]:
import os
import io
import pandas as pd
import numpy as np

# Predicting MPG (miles per gallon) ratings
# of cars based on
# Gallons per 100 miles, Cylinders, Displacement (100 cubic inches), Horsepower (100), Weight (1000 lbs)

df = pd.read_csv('AutoMPGModels.csv', header=0, error_bad_lines=False)

df.columns

b'Skipping line 394: expected 15 fields, saw 301\nSkipping line 395: expected 15 fields, saw 301\nSkipping line 396: expected 15 fields, saw 301\nSkipping line 397: expected 15 fields, saw 301\nSkipping line 398: expected 15 fields, saw 301\nSkipping line 399: expected 15 fields, saw 301\nSkipping line 400: expected 15 fields, saw 301\nSkipping line 401: expected 15 fields, saw 301\nSkipping line 402: expected 15 fields, saw 301\nSkipping line 404: expected 15 fields, saw 301\nSkipping line 405: expected 15 fields, saw 301\nSkipping line 415: expected 15 fields, saw 301\nSkipping line 425: expected 15 fields, saw 301\nSkipping line 435: expected 15 fields, saw 301\nSkipping line 445: expected 15 fields, saw 301\nSkipping line 455: expected 15 fields, saw 301\nSkipping line 465: expected 15 fields, saw 301\nSkipping line 476: expected 15 fields, saw 301\nSkipping line 477: expected 15 fields, saw 301\nSkipping line 478: expected 15 fields, saw 301\nSkipping line 479: expected 15 fields, saw 301\nSkipping line 480: expected 15 fields, saw 301\nSkipping line 481: expected 15 fields, saw 301\nSkipping line 482: expected 15 fields, saw 301\nSkipping line 483: expected 15 fields, saw 301\nSkipping line 484: expected 15 fields, saw 301\nSkipping line 489: expected 15 fields, saw 301\nSkipping line 490: expected 15 fields, saw 301\nSkipping line 491: expected 15 fields, saw 301\nSkipping line 492: expected 15 fields, saw 301\nSkipping line 493: expected 15 fields, saw 301\nSkipping line 494: expected 15 fields, saw 301\nSkipping line 495: expected 15 fields, saw 301\nSkipping line 496: expected 15 fields, saw 301\nSkipping line 497: expected 15 fields, saw 301\nSkipping line 498: expected 15 fields, saw 301\nSkipping line 499: expected 15 fields, saw 301\nSkipping line 501: expected 15 fields, saw 301\nSkipping line 502: expected 15 fields, saw 301\nSkipping line 503: expected 15 fields, saw 301\nSkipping line 504: expected 15 fields, saw 301\nSkipping line 505: expected 15 fields, saw 301\nSkipping line 506: expected 15 fields, saw 301\nSkipping line 507: expected 15 fields, saw 301\nSkipping line 508: expected 15 fields, saw 301\nSkipping line 509: expected 15 fields, saw 301\nSkipping line 510: expected 15 fields, saw 301\nSkipping line 512: expected 15 fields, saw 301\nSkipping line 513: expected 15 fields, saw 301\nSkipping line 529: expected 15 fields, saw 301\nSkipping line 545: expected 15 fields, saw 301\nSkipping line 563: expected 15 fields, saw 301\nSkipping line 564: expected 15 fields, saw 301\nSkipping line 565: expected 15 fields, saw 301\nSkipping line 566: expected 15 fields, saw 301\nSkipping line 567: expected 15 fields, saw 301\nSkipping line 568: expected 15 fields, saw 301\nSkipping line 569: expected 15 fields, saw 301\nSkipping line 570: expected 15 fields, saw 301\nSkipping line 571: expected 15 fields, saw 301\nSkipping line 572: expected 15 fields, saw 301\nSkipping line 573: expected 15 fields, saw 301\nSkipping line 575: expected 15 fields, saw 301\nSkipping line 576: expected 15 fields, saw 301\nSkipping line 577: expected 15 fields, saw 301\nSkipping line 578: expected 15 fields, saw 301\nSkipping line 579: expected 15 fields, saw 301\nSkipping line 580: expected 15 fields, saw 301\nSkipping line 581: expected 15 fields, saw 301\nSkipping line 582: expected 15 fields, saw 301\nSkipping line 583: expected 15 fields, saw 301\nSkipping line 584: expected 15 fields, saw 301\nSkipping line 586: expected 15 fields, saw 301\nSkipping line 587: expected 15 fields, saw 301\nSkipping line 603: expected 15 fields, saw 301\nSkipping line 619: expected 15 fields, saw 301\nSkipping line 637: expected 15 fields, saw 301\nSkipping line 638: expected 15 fields, saw 78\nSkipping line 639: expected 15 fields, saw 78\nSkipping line 640: expected 15 fields, saw 78\nSkipping line 641: expected 15 fields, saw 78\nSkipping line 642: expected 15 fields, saw 78\nSkipping line 643: expected 15 fields, saw 78\nSkipping line 644: expected 15 fields, saw 78\nSkipping line 645: expected 15 fields, saw 78\nSkipping line 646: expected 15 fields, saw 78\nSkipping line 647: expected 15 fields, saw 78\nSkipping line 649: expected 15 fields, saw 78\nSkipping line 650: expected 15 fields, saw 78\nSkipping line 651: expected 15 fields, saw 78\nSkipping line 652: expected 15 fields, saw 78\nSkipping line 654: expected 15 fields, saw 78\nSkipping line 655: expected 15 fields, saw 78\nSkipping line 656: expected 15 fields, saw 78\nSkipping line 657: expected 15 fields, saw 78\nSkipping line 658: expected 15 fields, saw 78\nSkipping line 660: expected 15 fields, saw 78\nSkipping line 662: expected 15 fields, saw 78\nSkipping line 663: expected 15 fields, saw 78\nSkipping line 664: expected 15 fields, saw 78\nSkipping line 665: expected 15 fields, saw 78\nSkipping line 666: expected 15 fields, saw 78\nSkipping line 667: expected 15 fields, saw 78\nSkipping line 682: expected 15 fields, saw 78\nSkipping line 683: expected 15 fields, saw 78\nSkipping line 684: expected 15 fields, saw 78\nSkipping line 687: expected 15 fields, saw 78\nSkipping line 690: expected 15 fields, saw 78\nSkipping line 709: expected 15 fields, saw 78\nSkipping line 731: expected 15 fields, saw 78\nSkipping line 753: expected 15 fields, saw 78\nSkipping line 775: expected 15 fields, saw 78\nSkipping line 799: expected 15 fields, saw 78\nSkipping line 800: expected 15 fields, saw 78\nSkipping line 801: expected 15 fields, saw 78\nSkipping line 802: expected 15 fields, saw 78\nSkipping line 803: expected 15 fields, saw 78\nSkipping line 804: expected 15 fields, saw 78\nSkipping line 805: expected 15 fields, saw 78\nSkipping line 806: expected 15 fields, saw 78\nSkipping line 807: expected 15 fields, saw 78\nSkipping line 808: expected 15 fields, saw 78\nSkipping line 809: expected 15 fields, saw 78\nSkipping line 811: expected 15 fields, saw 78\nSkipping line 812: expected 15 fields, saw 78\nSkipping line 813: expected 15 fields, saw 78\nSkipping line 814: expected 15 fields, saw 78\nSkipping line 815: expected 15 fields, saw 78\nSkipping line 816: expected 15 fields, saw 78\nSkipping line 817: expected 15 fields, saw 78\nSkipping line 818: expected 15 fields, saw 78\nSkipping line 819: expected 15 fields, saw 78\nSkipping line 820: expected 15 fields, saw 78\nSkipping line 821: expected 15 fields, saw 78\nSkipping line 823: expected 15 fields, saw 78\nSkipping line 824: expected 15 fields, saw 78\nSkipping line 825: expected 15 fields, saw 78\nSkipping line 826: expected 15 fields, saw 78\nSkipping line 827: expected 15 fields, saw 78\nSkipping line 829: expected 15 fields, saw 78\nSkipping line 830: expected 15 fields, saw 78\nSkipping line 831: expected 15 fields, saw 78\nSkipping line 834: expected 15 fields, saw 78\nSkipping line 837: expected 15 fields, saw 78\nSkipping line 856: expected 15 fields, saw 78\nSkipping line 878: expected 15 fields, saw 78\nSkipping line 900: expected 15 fields, saw 78\nSkipping line 922: expected 15 fields, saw 78\nSkipping line 946: expected 15 fields, saw 78\nSkipping line 947: expected 15 fields, saw 78\nSkipping line 948: expected 15 fields, saw 78\nSkipping line 949: expected 15 fields, saw 78\nSkipping line 950: expected 15 fields, saw 78\nSkipping line 951: expected 15 fields, saw 78\nSkipping line 952: expected 15 fields, saw 78\nSkipping line 953: expected 15 fields, saw 78\nSkipping line 954: expected 15 fields, saw 78\nSkipping line 955: expected 15 fields, saw 78\nSkipping line 956: expected 15 fields, saw 78\nSkipping line 958: expected 15 fields, saw 78\nSkipping line 959: expected 15 fields, saw 78\nSkipping line 960: expected 15 fields, saw 78\nSkipping line 961: expected 15 fields, saw 78\nSkipping line 962: expected 15 fields, saw 78\nSkipping line 963: expected 15 fields, saw 78\nSkipping line 964: expected 15 fields, saw 78\nSkipping line 965: expected 15 fields, saw 78\nSkipping line 966: expected 15 fields, saw 78\nSkipping line 967: expected 15 fields, saw 78\nSkipping line 969: expected 15 fields, saw 78\nSkipping line 970: expected 15 fields, saw 78\nSkipping line 971: expected 15 fields, saw 78\nSkipping line 972: expected 15 fields, saw 78\nSkipping line 973: expected 15 fields, saw 78\nSkipping line 975: expected 15 fields, saw 78\nSkipping line 976: expected 15 fields, saw 78\nSkipping line 977: expected 15 fields, saw 78\nSkipping line 980: expected 15 fields, saw 78\nSkipping line 983: expected 15 fields, saw 78\nSkipping line 1002: expected 15 fields, saw 78\nSkipping line 1024: expected 15 fields, saw 78\nSkipping line 1046: expected 15 fields, saw 78\nSkipping line 1068: expected 15 fields, saw 78\nSkipping line 1092: expected 15 fields, saw 78\nSkipping line 1093: expected 15 fields, saw 78\nSkipping line 1094: expected 15 fields, saw 78\nSkipping line 1095: expected 15 fields, saw 78\nSkipping line 1096: expected 15 fields, saw 78\nSkipping line 1097: expected 15 fields, saw 78\nSkipping line 1098: expected 15 fields, saw 78\nSkipping line 1099: expected 15 fields, saw 78\nSkipping line 1100: expected 15 fields, saw 78\nSkipping line 1101: expected 15 fields, saw 78\nSkipping line 1102: expected 15 fields, saw 78\nSkipping line 1104: expected 15 fields, saw 78\nSkipping line 1105: expected 15 fields, saw 78\nSkipping line 1106: expected 15 fields, saw 78\nSkipping line 1107: expected 15 fields, saw 78\nSkipping line 1108: expected 15 fields, saw 78\nSkipping line 1109: expected 15 fields, saw 78\nSkipping line 1111: expected 15 fields, saw 78\nSkipping line 1112: expected 15 fields, saw 78\nSkipping line 1113: expected 15 fields, saw 78\nSkipping line 1114: expected 15 fields, saw 78\nSkipping line 1115: expected 15 fields, saw 78\nSkipping line 1117: expected 15 fields, saw 78\nSkipping line 1118: expected 15 fields, saw 78\nSkipping line 1119: expected 15 fields, saw 78\nSkipping line 1122: expected 15 fields, saw 78\nSkipping line 1125: expected 15 fields, saw 78\nSkipping line 1144: expected 15 fields, saw 78\nSkipping line 1166: expected 15 fields, saw 78\nSkipping line 1188: expected 15 fields, saw 78\nSkipping line 1210: expected 15 fields, saw 78\nSkipping line 1234: expected 15 fields, saw 78\nSkipping line 1235: expected 15 fields, saw 85\nSkipping line 1236: expected 15 fields, saw 85\nSkipping line 1237: expected 15 fields, saw 85\nSkipping line 1238: expected 15 fields, saw 85\nSkipping line 1239: expected 15 fields, saw 85\nSkipping line 1240: expected 15 fields, saw 85\nSkipping line 1241: expected 15 fields, saw 85\nSkipping line 1242: expected 15 fields, saw 85\nSkipping line 1243: expected 15 fields, saw 85\nSkipping line 1244: expected 15 fields, saw 85\nSkipping line 1246: expected 15 fields, saw 85\nSkipping line 1247: expected 15 fields, saw 85\nSkipping line 1248: expected 15 fields, saw 85\nSkipping line 1249: expected 15 fields, saw 85\nSkipping line 1250: expected 15 fields, saw 85\nSkipping line 1251: expected 15 fields, saw 85\nSkipping line 1253: expected 15 fields, saw 85\nSkipping line 1254: expected 15 fields, saw 85\nSkipping line 1255: expected 15 fields, saw 85\nSkipping line 1256: expected 15 fields, saw 85\nSkipping line 1257: expected 15 fields, saw 85\nSkipping line 1259: expected 15 fields, saw 85\nSkipping line 1260: expected 15 fields, saw 85\nSkipping line 1261: expected 15 fields, saw 85\nSkipping line 1264: expected 15 fields, saw 85\nSkipping line 1265: expected 15 fields, saw 85\nSkipping line 1266: expected 15 fields, saw 85\nSkipping line 1267: expected 15 fields, saw 85\nSkipping line 1268: expected 15 fields, saw 85\nSkipping line 1269: expected 15 fields, saw 85\nSkipping line 1270: expected 15 fields, saw 85\nSkipping line 1271: expected 15 fields, saw 85\nSkipping line 1272: expected 15 fields, saw 85\nSkipping line 1273: expected 15 fields, saw 85\nSkipping line 1274: expected 15 fields, saw 85\nSkipping line 1275: expected 15 fields, saw 85\nSkipping line 1276: expected 15 fields, saw 85\nSkipping line 1277: expected 15 fields, saw 85\nSkipping line 1278: expected 15 fields, saw 85\nSkipping line 1279: expected 15 fields, saw 85\nSkipping line 1280: expected 15 fields, saw 85\nSkipping line 1281: expected 15 fields, saw 85\nSkipping line 1282: expected 15 fields, saw 85\nSkipping line 1283: expected 15 fields, saw 85\nSkipping line 1284: expected 15 fields, saw 85\nSkipping line 1285: expected 15 fields, saw 85\nSkipping line 1286: expected 15 fields, saw 85\nSkipping line 1287: expected 15 fields, saw 85\nSkipping line 1288: expected 15 fields, saw 85\nSkipping line 1289: expected 15 fields, saw 85\nSkipping line 1290: expected 15 fields, saw 85\nSkipping line 1291: expected 15 fields, saw 85\nSkipping line 1292: expected 15 fields, saw 85\nSkipping line 1293: expected 15 fields, saw 85\nSkipping line 1294: expected 15 fields, saw 85\nSkipping line 1295: expected 15 fields, saw 85\nSkipping line 1296: expected 15 fields, saw 85\nSkipping line 1319: expected 15 fields, saw 85\nSkipping line 1322: expected 15 fields, saw 85\nSkipping line 1341: expected 15 fields, saw 85\nSkipping line 1363: expected 15 fields, saw 85\nSkipping line 1385: expected 15 fields, saw 85\nSkipping line 1407: expected 15 fields, saw 85\nSkipping line 1431: expected 15 fields, saw 85\nSkipping line 1432: expected 15 fields, saw 26\nSkipping line 1433: expected 15 fields, saw 26\nSkipping line 1434: expected 15 fields, saw 26\nSkipping line 1435: expected 15 fields, saw 26\nSkipping line 1436: expected 15 fields, saw 26\nSkipping line 1437: expected 15 fields, saw 26\nSkipping line 1439: expected 15 fields, saw 26\nSkipping line 1440: expected 15 fields, saw 26\nSkipping line 1441: expected 15 fields, saw 26\nSkipping line 1443: expected 15 fields, saw 26\nSkipping line 1444: expected 15 fields, saw 26\nSkipping line 1445: expected 15 fields, saw 26\nSkipping line 1446: expected 15 fields, saw 26\nSkipping line 1447: expected 15 fields, saw 26\nSkipping line 1448: expected 15 fields, saw 26\nSkipping line 1450: expected 15 fields, saw 26\nSkipping line 1451: expected 15 fields, saw 26\nSkipping line 1452: expected 15 fields, saw 26\nSkipping line 1453: expected 15 fields, saw 26\nSkipping line 1454: expected 15 fields, saw 26\nSkipping line 1456: expected 15 fields, saw 26\nSkipping line 1457: expected 15 fields, saw 26\nSkipping line 1458: expected 15 fields, saw 26\nSkipping line 1459: expected 15 fields, saw 26\nSkipping line 1461: expected 15 fields, saw 26\nSkipping line 1462: expected 15 fields, saw 26\nSkipping line 1464: expected 15 fields, saw 26\nSkipping line 1465: expected 15 fields, saw 26\nSkipping line 1466: expected 15 fields, saw 26\nSkipping line 1467: expected 15 fields, saw 26\nSkipping line 1468: expected 15 fields, saw 26\nSkipping line 1469: expected 15 fields, saw 26\nSkipping line 1470: expected 15 fields, saw 26\nSkipping line 1471: expected 15 fields, saw 26\nSkipping line 1472: expected 15 fields, saw 26\nSkipping line 1473: expected 15 fields, saw 26\nSkipping line 1474: expected 15 fields, saw 26\nSkipping line 1475: expected 15 fields, saw 26\nSkipping line 1476: expected 15 fields, saw 26\nSkipping line 1477: expected 15 fields, saw 26\nSkipping line 1478: expected 15 fields, saw 26\nSkipping line 1479: expected 15 fields, saw 26\nSkipping line 1480: expected 15 fields, saw 26\nSkipping line 1481: expected 15 fields, saw 26\nSkipping line 1482: expected 15 fields, saw 26\nSkipping line 1483: expected 15 fields, saw 26\nSkipping line 1484: expected 15 fields, saw 26\nSkipping line 1485: expected 15 fields, saw 26\nSkipping line 1486: expected 15 fields, saw 26\nSkipping line 1487: expected 15 fields, saw 26\nSkipping line 1488: expected 15 fields, saw 26\nSkipping line 1489: expected 15 fields, saw 26\nSkipping line 1490: expected 15 fields, saw 26\nSkipping line 1491: expected 15 fields, saw 26\nSkipping line 1492: expected 15 fields, saw 26\nSkipping line 1493: expected 15 fields, saw 26\nSkipping line 1494: expected 15 fields, saw 26\nSkipping line 1495: expected 15 fields, saw 26\nSkipping line 1498: expected 15 fields, saw 21\nSkipping line 1499: expected 15 fields, saw 21\nSkipping line 1500: expected 15 fields, saw 21\nSkipping line 1501: expected 15 fields, saw 21\nSkipping line 1502: expected 15 fields, saw 21\nSkipping line 1503: expected 15 fields, saw 21\nSkipping line 1504: expected 15 fields, saw 21\nSkipping line 1505: expected 15 fields, saw 21\nSkipping line 1506: expected 15 fields, saw 21\nSkipping line 1507: expected 15 fields, saw 21\nSkipping line 1508: expected 15 fields, saw 21\nSkipping line 1509: expected 15 fields, saw 21\nSkipping line 1510: expected 15 fields, saw 21\nSkipping line 1511: expected 15 fields, saw 21\nSkipping line 1512: expected 15 fields, saw 21\nSkipping line 1516: expected 15 fields, saw 21\nSkipping line 1517: expected 15 fields, saw 21\nSkipping line 1518: expected 15 fields, saw 21\nSkipping line 1519: expected 15 fields, saw 21\nSkipping line 1520: expected 15 fields, saw 21\nSkipping line 1521: expected 15 fields, saw 21\nSkipping line 1522: expected 15 fields, saw 21\nSkipping line 1523: expected 15 fields, saw 21\nSkipping line 1524: expected 15 fields, saw 21\nSkipping line 1525: expected 15 fields, saw 21\nSkipping line 1528: expected 15 fields, saw 21\nSkipping line 1529: expected 15 fields, saw 21\nSkipping line 1530: expected 15 fields, saw 21\nSkipping line 1531: expected 15 fields, saw 21\nSkipping line 1532: expected 15 fields, saw 21\nSkipping line 1533: expected 15 fields, saw 21\nSkipping line 1534: expected 15 fields, saw 21\nSkipping line 1535: expected 15 fields, saw 21\nSkipping line 1536: expected 15 fields, saw 21\nSkipping line 1537: expected 15 fields, saw 21\nSkipping line 1538: expected 15 fields, saw 21\nSkipping line 1539: expected 15 fields, saw 21\nSkipping line 1540: expected 15 fields, saw 21\nSkipping line 1541: expected 15 fields, saw 21\nSkipping line 1545: expected 15 fields, saw 21\nSkipping line 1546: expected 15 fields, saw 21\nSkipping line 1547: expected 15 fields, saw 21\nSkipping line 1548: expected 15 fields, saw 21\nSkipping line 1549: expected 15 fields, saw 21\nSkipping line 1553: expected 15 fields, saw 21\nSkipping line 1554: expected 15 fields, saw 21\nSkipping line 1555: expected 15 fields, saw 21\nSkipping line 1556: expected 15 fields, saw 21\nSkipping line 1557: expected 15 fields, saw 21\nSkipping line 1558: expected 15 fields, saw 21\nSkipping line 1559: expected 15 fields, saw 21\nSkipping line 1560: expected 15 fields, saw 21\nSkipping line 1561: expected 15 fields, saw 21\nSkipping line 1562: expected 15 fields, saw 21\nSkipping line 1563: expected 15 fields, saw 21\nSkipping line 1564: expected 15 fields, saw 21\nSkipping line 1565: expected 15 fields, saw 21\nSkipping line 1566: expected 15 fields, saw 21\nSkipping line 1567: expected 15 fields, saw 21\nSkipping line 1568: expected 15 fields, saw 21\nSkipping line 1569: expected 15 fields, saw 21\nSkipping line 1570: expected 15 fields, saw 21\nSkipping line 1571: expected 15 fields, saw 21\nSkipping line 1573: expected 15 fields, saw 21\nSkipping line 1574: expected 15 fields, saw 21\nSkipping line 1575: expected 15 fields, saw 21\nSkipping line 1576: expected 15 fields, saw 21\nSkipping line 1577: expected 15 fields, saw 21\n'

Index(['GallonsPer100Miles', 'GallonsPer100MilesTo1981', 'MPG', 'Cylinders',
       'Displacement100ci', 'Horsepower100', 'Weight1000lb', 'Seconds0to60',
       'Year', 'Year70To81', 'Origin', 'Origin.Eq.1', 'Origin.Eq.2',
       'Origin.Eq.3', 'Name'],
      dtype='object')

In [129]:
# change column indexes to numeric
# for convenience
df.columns = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 , 12, 13, 14]

# drop less important columns
df.drop(axis=1, columns=[1, 7, 8, 9, 10, 11, 12, 13, 14], inplace=True)

df.head()

     0     2    3     4     5      6
0  5.6  18.0  8.0  3.07  1.30  3.504
1  6.7  15.0  8.0  3.50  1.65  3.693
2  5.6  18.0  8.0  3.18  1.50  3.436
3  6.3  16.0  8.0  3.04  1.50  3.433
4  5.9  17.0  8.0  3.02  1.40  3.449

In [130]:
# rename column names for convenience
df.columns = ['x1', 'y', 'x2', 'x3', 'x4', 'x5']

df.head()

    x1     y   x2    x3    x4     x5
0  5.6  18.0  8.0  3.07  1.30  3.504
1  6.7  15.0  8.0  3.50  1.65  3.693
2  5.6  18.0  8.0  3.18  1.50  3.436
3  6.3  16.0  8.0  3.04  1.50  3.433
4  5.9  17.0  8.0  3.02  1.40  3.449

In [131]:
# drop rows with null values
df.dropna(axis=0, inplace=True)

df

      x1     y   x2    x3    x4     x5
0    5.6  18.0  8.0  3.07  1.30  3.504
1    6.7  15.0  8.0  3.50  1.65  3.693
2    5.6  18.0  8.0  3.18  1.50  3.436
3    6.3  16.0  8.0  3.04  1.50  3.433
4    5.9  17.0  8.0  3.02  1.40  3.449
..   ...   ...  ...   ...   ...    ...
387  3.7  27.0  4.0  1.40  0.86  2.790
388  2.3  44.0  4.0  0.97  0.52  2.130
389  3.1  32.0  4.0  1.35  0.84  2.295
390  3.6  28.0  4.0  1.20  0.79  2.625
391  3.2  31.0  4.0  1.19  0.82  2.720

[392 rows x 6 columns]

In [132]:
def make_numeric(column_series):
    column_series = pd.to_numeric(column_series)
    return column_series

df = df.apply(make_numeric, axis=1)

df['x1']

0      5.6
1      6.7
2      5.6
3      6.3
4      5.9
      ...
387    3.7
388    2.3
389    3.1
390    3.6
391    3.2
Name: x1, Length: 392, dtype: float64

In [133]:
thetas = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

In [134]:
count = 0
for i in range(10):
    
    print("iteration number:", count)
    count += 1
    h = sum([(thetas[0] + (thetas[i] * df['x' + str(i)])) for i in range(1, 6)])
    
    print('h: ', h)
    
    sq_error = np.sum((h - df['y']) ** 2)

    m = len(df)

    J = (1/(2*m))*sq_error

    print('J: ', J)


    # Gradinet Descent

    alpha = 0.01
    diff_J_theta0 = 0
    diff_J_theta1 = 0
    diff_J_theta2 = 0
    diff_J_theta3 = 0
    diff_J_theta4 = 0
    diff_J_theta5 = 0

    diff_J_theta0 = np.sum(h - df['y'])
    diff_J_theta1 = np.sum((h - df['y']) * df['x1'])
    diff_J_theta2 = np.sum((h - df['y']) * df['x2'])
    diff_J_theta3 = np.sum((h - df['y']) * df['x3'])
    diff_J_theta4 = np.sum((h - df['y']) * df['x4'])
    diff_J_theta5 = np.sum((h - df['y']) * df['x5'])

    thetas[0] = thetas[0] - (alpha/m) * diff_J_theta0 
    thetas[1] = thetas[1] - (alpha/m) * diff_J_theta1
    thetas[2] = thetas[2] - (alpha/m) * diff_J_theta1
    thetas[3] = thetas[3] - (alpha/m) * diff_J_theta1
    thetas[4] = thetas[4] - (alpha/m) * diff_J_theta1
    thetas[5] = thetas[5] - (alpha/m) * diff_J_theta1

    print ('thetas: ', thetas[0],thetas[1], thetas[2], thetas[3], thetas[4], thetas[5])

iteration number: 0
h:  0      13.2370
1      14.2715
2      13.3580
3      13.6365
4      13.3845
        ...
387     8.8750
388     7.4600
389     8.2925
390     8.6075
391     8.4650
Length: 392, dtype: float64
J:  134.81848304017856
thetas:  0.6283440306122449 0.9500493596938775 0.9500493596938775 0.9500493596938775 0.9500493596938775 0.9500493596938775
iteration number: 1
h:  0      23.543080
1      25.508732
2      23.772992
3      24.302170
4      23.823345
         ...
387    15.254849
388    12.566210
389    14.148042
390    14.746573
391    14.475809
Length: 392, dtype: float64
J:  90.50204503956822
thetas:  0.6772592143005276 0.9819336754779298 0.9819336754779298 0.9819336754779298 0.9819336754779298 0.9819336754779298
iteration number: 2
h:  0      24.472340
1      26.503961
2      24.709968
3      25.256905
4      24.762010
         ...
387    15.905950
388    13.127078
389    14.761998
390    15.380616
391    15.100765
Length: 392, dtype: float64
J:  89.13663900815399
thetas:  0.7185560364942446 0.9746656392634728 0.9746656392634728 0.9746656392634728 0.9746656392634728 0.9746656392634728
iteration number: 3
h:  0      24.522750
1      26.539333
2      24.758619
3      25.301508
4      24.810276
         ...
387    16.019767
388    13.261463
389    14.884282
390    15.498321
391    15.220541
Length: 392, dtype: float64
J:  88.30010895755753
thetas:  0.7589671133182562 0.9637752360679444 0.9637752360679444 0.9637752360679444 0.9637752360679444 0.9637752360679444
iteration number: 4
h:  0      24.490945
1      26.484996
2      24.724179
3      25.261001
4      24.775259
         ...
387    16.082970
388    13.355486
389    14.960172
390    15.567350
391    15.292674
Length: 392, dtype: float64
J:  87.48949865202967
thetas:  0.7991243897452746 0.9525929689346242 0.9525929689346242 0.9525929689346242 0.9525929689346242 0.9525929689346242
iteration number: 5
h:  0      24.451603
1      26.422518
2      24.682131
3      25.212725
4      24.732618
         ...
387    16.141182
388    13.445344
389    15.031411
390    15.631545
391    15.360056
Length: 392, dtype: float64
J:  86.68810890385566
thetas:  0.8390879049711236 0.941430829951662 0.941430829951662 0.941430829951662 0.941430829951662 0.941430829951662
iteration number: 6
h:  0      24.411725
1      26.359546
2      24.639551
3      25.163928
4      24.689447
         ...
387    16.198683
388    13.534433
389    15.101916
390    15.695017
391    15.426709
Length: 392, dtype: float64
J:  85.89457448516485
thetas:  0.8788640816598675 0.9303178446054647 0.9303178446054647 0.9303178446054647 0.9303178446054647 0.9303178446054647
iteration number: 7
h:  0      24.371966
1      26.296793
2      24.597103
3      25.115290
4      24.646410
         ...
387    16.255873
388    13.623073
389    15.172053
390    15.758153
391    15.493012
Length: 392, dtype: float64
J:  85.10870338162069
thetas:  0.918454312528822 0.9192565129654593 0.9192565129654593 0.9192565129654593 0.9192565129654593 0.9192565129654593
iteration number: 8
h:  0      24.332386
1      26.234328
2      24.554846
3      25.066872
4      24.603567
         ...
387    16.312792
388    13.711296
389    15.241858
390    15.820990
391    15.559002
Length: 392, dtype: float64
J:  84.33041194518923
thetas:  0.9578595150724089 0.9082468495316457 0.9082468495316457 0.9082468495316457 0.9082468495316457 0.9082468495316457
iteration number: 9
h:  0      24.292990
1      26.172153
2      24.512786
3      25.018680
4      24.560923
         ...
387    16.369445
388    13.799106
389    15.311337
390    15.883533
391    15.624682
Length: 392, dtype: float64
J:  83.55962729242835
thetas:  0.997080558557989 0.8972886368240514 0.8972886368240514 0.8972886368240514 0.8972886368240514 0.8972886368240514